version: '3.8'

services:
  # Backend service - development mode
  charactercut-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: charactercut-backend-dev
    ports:
      - "8000:8000"
    environment:
      - STAGE=development
      - PORT=8000
      - PYTHONPATH=/app
    volumes:
      # Mount entire backend for live development
      - ./backend:/app:rw
    restart: unless-stopped
    command: ["uvicorn", "simple_main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - charactercut-network

  # Frontend service - development mode with hot reload
  charactercut-frontend:
    image: node:18-alpine
    container_name: charactercut-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite dev server
    environment:
      - VITE_API_URL=http://charactercut-backend:8000
    volumes:
      # Mount source for hot reload
      - .:/app:rw
      - /app/node_modules
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      charactercut-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - charactercut-network

networks:
  charactercut-network:
    driver: bridge